apiVersion: v1
kind: Secret
metadata:
  name: minio-bucket-controller-credentials
  namespace: minio-bucket-controller-system
stringData:
  MINIO_ACCESS_KEY: <ACCESS_KEY>
  MINIO_SECRET_KEY: <SECRET_KEY>
---
apiVersion: s3.linka.cloud/v1alpha1
kind: BucketProvider
metadata:
  name: my-bucket-provider
  annotations:
    s3.linka.cloud/is-default-provider: ""
spec:
  endpoint: myminio:9000
  # uncomment if you don't use tls
  # insecure: true
  accessKey:
    name: minio-bucket-controller-credentials
    namespace: minio-bucket-controller-system
    key: MINIO_ACCESS_KEY
  secretKey:
    name: minio-bucket-controller-credentials
    namespace: minio-bucket-controller-system
    key: MINIO_SECRET_KEY
